version: '2'

services:
    kibana:
        image: kibana:5.2.1
        ports:
            - "5601:5601"
        links:
          - elasticsearch

    elasticsearch:
        image: elasticsearch:5.2.2
        ports:
            - "9200:9200"
